OpenTelemetry instrumentation Helm chart to install

diff --git a/tests/soak/Dockerfile b/tests/soak/Dockerfile
--- a/tests/soak/Dockerfile
+++ b/tests/soak/Dockerfile
@@ -1,6 +1,8 @@
 FROM debian:bookworm
-ARG LK_VERSION=v2.2.0
-ARG CKPY_VERSION=v2.2.0
+ARG LK_VERSION
+ARG CKPY_VERSION
+RUN test -n "${LK_VERSION}" || (echo "LK_VERSION env variable required" && exit 1)
+RUN test -n "${CKPY_VERSION}" || (echo "CKPY_VERSION env variable required" && exit 1)
 ENV DEBIAN_FRONTEND=noninteractive
 RUN apt update && apt install -y sudo
 RUN mkdir -p /soaktests
